openapi: 3.0.0
info:
  title: Beengala API
  version: 1.0.0
  description: API for Beengala application

tags:
  - name: Auth
    description: Endpoints for authentication

paths:
  paths:
  /auth/login:
    post:
      summary: User login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        200:
          description: Login successful, token and user data returned
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Artist'
                  - $ref: '#/components/schemas/Buyer'
        400:
          description: Email and password are required
        401:
          description: Incorrect email or password
        500:
          description: Internal server error

components:
  schemas:
    Artist:
      type: object
      properties:
        userId:
          type: integer
        userType:
          type: string
        name:
          type: string
        lastname:
          type: string
        email:
          type: string
        semblance:
          type: string
        art_style:
          type: string
        birthday:
          type: string
          format: date
        origin:
          type: string
        sex:
          type: string
        city:
          type: string

    Buyer:
      type: object
      properties:
        userId:
          type: integer
        userType:
          type: string
        name:
          type: string
        lastname:
          type: string
        email:
          type: string
        buyer_type:
          type: string
        art_styles:
          type: string
        birthday:
          type: string
          format: date
        origin:
          type: string
        sex:
          type: string
        city:
          type: string