openapi: 3.0.0
info:
  title: Beengala API
  version: 1.0.0
  description: API for Beengala application

tags:
  - name: Artists
    description: Operations related to Artists

paths:
  /artists:
    get:
      summary: Get a list of all artists
      tags:
        - Artist
      security:
        - bearerAuth: []
      responses:
        200:
          description: A list of artists with detailed profile information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artist'
        401:
          description: Unauthorized access - valid authentication token required
        500:
          description: Internal server error

components:
  schemas:
    Artist:
      type: object
      properties:
        userId:
          type: integer
        userType:
          type: string
        name:
          type: string
        lastname:
          type: string
        email:
          type: string
          format: email
        semblance:
          type: string
        art_style:
          type: string
        birthday:
          type: string
          format: date
        origin:
          type: string
        sex:
          type: string
        city:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
